- name: Template snmpd.conf
  template: src=/srv/ansible/roles/snmp/templates/etc-snmp-snmpd-conf.j2 dest=/etc/snmp/snmpd.conf owner=root group=root mode=644 backup=yes

- name: Enable snmpd service
  service: 
    name: snmpd 
    enabled: yes
    state: restarted

