---
- name: Set up variables
  include_vars: "{{ item }}"
  with_first_found:
        - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
        - "../vars/{{ ansible_distribution }}.yml"
        - "../vars/{{ ansible_os_family }}.yml"
        - "../vars/default.yml"

- name: Signal Sciences config path
  file:
      path: /etc/nginx/sigsci
      state: directory

- name: Signal Sciences config file
  template:
      src: ../templates/sigsci_agent.conf.j2
      dest: /etc/nginx/sigsci/agent.conf
      owner: root
      group: root
      mode: 0644
      trim_blocks: false

- name: Add nginx directories
  file:
      path: '/etc/nginx/{{ item.path }}'
      state: directory
      mode: '{{ item.mode }}'
      owner: root
      group: root
  with_filetree: ../templates/nginx
  when: item.state == 'directory'

- name: Add nginx base data
  synchronize:
      src: '../templates/nginx/'
      dest: '/etc/nginx/'

- name: Add nginx main config
  template:
      src: '../templates/nginx.conf.j2'
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
      trim_blocks: false

- name: Add nginx machine config
  template:
      src: '../templates/ansible.conf.j2'
      dest: /etc/nginx/ansible.conf
      owner: root
      group: root
      mode: 0644
      trim_blocks: false

- name: Add latest certbot certificates
  synchronize:
      src: '/etc/letsencrypt/live/'
      dest: '/etc/nginx/certs/'
      archive: false
      recursive: true
      copy_links: true

- name: Add nginx injected configuration
  copy:
      dest: '/etc/nginx/{{ item.key }}'
      content: '{{ item.value }}'
      owner: root
      group: root
  with_dict: '{{ nginx_includes }}'

