---
  - name: Install Packages
    yum: name={{ item }} state=present
    with_items:
        - unbound
        - bind-utils
        - cockpit
    when: ansible_os_family == "RedHat"

  - name: Allow cockpit Through Firewall
    firewalld:
        service: cockpit
        permanent: true
        state: enabled
    when: ansible_os_family == "RedHat"
    
  - name: Allow unbound Through Firewall
    firewalld:
       service: dns
       permanent: true
       state: enabled
    when: ansible_os_family == "RedHat"

  - name: Enable and start cockpit
    service:
      name: cockpit
      enabled: yes
      state: started

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted

  - name: Copy unbound config
    copy:
      src: /srv/ansible/roles/fileserver/files/unbound.conf
      dest: /etc/unbound/unbound.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Enable and start unbound
    service:
      name: unbound
      enabled: yes
      state: started
