---
- name: CentOS/RHEL Updates.
  yum: 
    update_cache: yes
    name: "*"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Deb Updates
  apt: 
    update_cache: yes
    upgrade: yes
  when: ansible_os_family == 'Debian'

- name: Get EPEL
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Install rhel specific packages
  yum: 
    name:
      - wget
      - sysstat
      - libsemanage-python
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Common Packages
  package:
    name:
      - vim
      - telnet
      - rsync
      - git
      - iotop
      - sysstat
      - ntp
      - ntpdate
      - strace
      - psmisc
      - ncdu
      - lsof
      - mtr
      - mercurial
      - ltrace
      - htop
    state: present

- name: Allow rsyncd through firewall
  firewalld:
      service: rsyncd
      permanent: true
      state: enabled
  when: ansible_os_family == "RedHat"

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  when: ansible_os_family == "RedHat"
