---
- name: CentOS/RHEL Updates.
  yum: 
    update_cache: yes
    name: "*"
    state: latest
  when: >
    ansible_os_family == 'RedHat'

- name: Deb Updates
  apt: 
    update_cache: yes
    upgrade: yes
  when: >
    ansible_os_family == 'Debian'

- name: Install rhel specific packages
  yum: name={{ item }} state=present
  with_items:
      - wget
      - sysstat
  when: ansible_os_family == "RedHat"

- name: Get EPEL
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm
    state: present


- name: Install Common Packages
  package: name={{ item }} state=present
  with_items:
      - vim
      - telnet
      - rsync
      - git
      - iotop
      - sysstat
      - ntp
      - ntpdate
      - strace
      - psmisc
      - ncdu
      - lsof
      - mtr
      - mercurial
      - ltrace
      - htop

- name: Allow rsyncd through firewall
  firewalld:
      service: rsyncd
      permanent: true
      state: enabled
  when: ansible_os_family == "RedHat"

- name: restart firewalld
  service:
    name: firewalld
    state: restarted
  when: ansible_os_family == "RedHat"
