- name: Install Common Packages
  package:
    name:
      - vim
      - telnet
      - rsync
      - git
      - iotop
      - sysstat
      - strace
      - psmisc
      - ncdu
      - lsof
      - mtr
      - ltrace
      - htop
      - snmpd 
      - etckeeper
